import asyncio
import logging
import websockets
import aiohttp
import json
import os
from datetime import datetime
from dotenv import load_dotenv

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")

file_handler = logging.FileHandler("bot.log", encoding="utf-8")
file_handler.setLevel(logging.DEBUG)
file_handler.setFormatter(formatter)

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)
console_handler.setFormatter(formatter)

load_dotenv()

discordwh_url = os.getenv("DISCORD_WEBHOOK")
raw_wh = os.getenv("RAW_D_WH")

if not logger.handlers:
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)

wolfxurl = "wss://ws-api.wolfx.jp/jma_eew"
p2purl = "wss://api.p2pquake.net/v2/ws"


async def wsconnect(name, url, session):
    while True:
        try:
            async with websockets.connect(url) as websocket:
                logger.info(f"{name} successfully connected")
                async for message in websocket:
                    try:
                        parsed_json = json.loads(message)
                    except json.JSONDecodeError as e:
                        logger.error(f"{name} JSON parse error:\n{e}")
                        continue

                    logger.debug(f"{name} data received: {message}")

                    if name == "wolfx":
                        type = parsed_json.get("type", "不明")

                        if type == "jma_eew":
                            isWarn = parsed_json.get("isWarn", False)
                            Serial = parsed_json.get("Serial", "不明")
                            Title = parsed_json.get("Title", "不明")
                            Hypocenter = parsed_json.get("Hypocenter", "不明")
                            Magunitude = parsed_json.get("Magunitude", "不明")
                            Depth = parsed_json.get("Depth", "不明")
                            AnnouncedTime = parsed_json.get("AnnouncedTime", "不明")
                            MaxIntensity = parsed_json.get("MaxIntensity", "不明")
                            isFinal = parsed_json.get("isFinal", False)
                            isCancel = parsed_json.get("isCancel", False)

                            logger.info(f"{name}:{Title} 第{Serial}報")

                            wh_title = f"{Title} 第{Serial}報"
                            if isFinal:
                                wh_title += " - 最終"
                            if isCancel:
                                wh_title += "- 取消"

                            if isWarn:
                                W_Area = [area["Chiiki"] for area in parsed_json["WarnArea"]]
                                W_Area_send = "\u3000".join(W_Area)

                                d_message = {
                                    "embeds": [
                                        {
                                            "title": f"{wh_title}",
                                            "color": 0xb2002f,
                                            "description": f"{Hypocenter}で地震\u3000身の安全を確保してください\nM {Magunitude}\u3000深さ {Depth}km",
                                            "fields": [
                                                {
                                                    "name": "推定最大震度",
                                                    "value": f"{MaxIntensity}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "対象地域",
                                                    "value": f"{W_Area_send}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "発表時刻",
                                                    "value": f"{AnnouncedTime}",
                                                    "inline": False
                                                }
                                            ]

                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---⚠{wh_title}⚠---\n{Hypocenter}で地震\n身の安全を確保してください\nM {Magunitude}\u3000深さ {Depth}km\n推定最大震度 {MaxIntensity}\n対象地域\n{W_Area_send}\n発表時刻 {AnnouncedTime}\n[Generated by EQFast]"
                                }

                            else:
                                d_message = {
                                    "embeds": [
                                        {
                                            "title": f"{wh_title}",
                                            "color": 0xccb100,
                                            "description": f"{Hypocenter}で地震\nM {Magunitude}\u3000深さ {Depth}km",
                                            "fields": [
                                                {
                                                    "name": "推定最大震度",
                                                    "value": f"{MaxIntensity}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "発表時刻",
                                                    "value": f"{AnnouncedTime}",
                                                    "inline": False
                                                }
                                            ]

                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---{wh_title}---\n{Hypocenter}で地震\nM {Magunitude}\u3000深さ {Depth}km\n推定最大震度 {MaxIntensity}\n発表時刻 {AnnouncedTime}\n[Generated by EQFast]"
                                }

                            async with session.post(discordwh_url, json=d_message) as resp:
                                if resp.status in (200, 204):
                                    logger.info(f"Webhook OK:{resp.status}")
                                else:
                                    logger.error(f"Webhook failed:{resp.status}")

                            async with session.post(raw_wh, json=sub_message) as resp:
                                if resp.status in (200, 204):
                                    logger.info(f"raw_Webhook OK:{resp.status}")
                                else:
                                    logger.error(f"raw_Webhook failed:{resp.status}")

                        elif type == "不明":
                            logger.warning(f"{name} unknown data type received")

                    elif name == "p2p":
                        code = parsed_json.get("code", None)

                        if code == 551:
                            hyponame = parsed_json["earthquake"]["hypocenter"]["name"]
                            time = parsed_json["earthquake"]["time"]
                            maxscale_raw = parsed_json["earthquake"]["maxScale"]
                            magnitude = str(parsed_json["earthquake"]["hypocenter"]["magnitude"])
                            depth = str(parsed_json["earthquake"]["hypocenter"]["depth"])
                            tsunami = parsed_json["earthquake"]["domesticTsunami"]
                            source = parsed_json["issue"]["source"]
                            type = parsed_json["issue"]["type"]

                            if depth == 0:
                                depth = "ごく浅い"
                            elif depth == -1:
                                depth = "不明"

                            if "." not in magnitude:
                                magnitude += ".0"

                            ms = {
                                -1: "None",
                                46: "未入電",
                                10: "1",
                                20: "2",
                                30: "3",
                                40: "4",
                                45: "5弱",
                                50: "5強",
                                55: "6弱",
                                60: "6強",
                                70: "7",
                            }

                            maxscale = ms.get(int(maxscale_raw), "不明")

                            if hyponame == "":
                                hyponame = "None"

                            if magnitude == "-1":
                                magnitude = "None"

                            tsunamistr = {
                                "None": "この地震による津波の心配はありません。",
                                "Unknown": "津波に関する情報は不明です。",
                                "Checking": "津波などの詳しい情報は追ってお知らせします。",
                                "NonEffective": "若干の海面変動があるかも知れませんが、被害の心配はありません。",
                                "Watch": "現在、津波注意報が発表されています。",
                                "Warning": "現在、津波予報等を発表中です。"
                            }

                            tsunami_info = tsunamistr[tsunami]

                            try:
                                # timeの秒を削除
                                time = datetime.strptime(time, "%Y/%m/%d %H:%M:%S")
                                time = time.strftime("%d日 %H:%M")
                            except Exception:
                                pass

                            if type == "ScalePrompt":
                                d_message = {
                                    "embeds": [
                                        {
                                            "title": "震度速報",
                                            "description": f"{time}頃、地震がありました。\n{tsunami_info}",
                                            "color": 0x007cbf,
                                            "fields": [
                                                {
                                                    "name": "最大震度",
                                                    "value": f"{maxscale}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "発生時刻",
                                                    "value": f"{time}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "ソース",
                                                    "value": f"{source}",
                                                    "inline": False
                                                }
                                            ]
                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---震度速報---\n{time}頃、地震がありました。\n{tsunami_info}\n\n最大震度 {maxscale}\n発生時刻 {time}\n ソース {source}\n[Generated by EQFast]"
                                }

                            elif type == "Destination":
                                d_message = {
                                    "embeds": [
                                        {
                                            "title": "震源に関する情報",
                                            "description": f"{time}頃、{hyponame}で地震がありました。\n{tsunami_info}",
                                            "color": 0x007cbf,
                                            "fields": [
                                                {
                                                    "name": "震源",
                                                    "value": f"{hyponame}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "M",
                                                    "value": f"{magnitude}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "深さ",
                                                    "value": f"{depth}km",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "発生時刻",
                                                    "value": f"{time}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "ソース",
                                                    "value": f"{source}",
                                                    "inline": False
                                                }
                                            ]
                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---震源に関する情報---\n{time}頃、{hyponame}で地震がありました。\n{tsunami_info}\n\n震源 {hyponame}\nM {magnitude}\n深さ {depth}km\n発生時刻 {time}\nソース {source}\n\n[Generated by EQFast]"
                                }

                            elif type == "ScaleAndDestination":
                                d_message = {
                                    "embeds": [
                                        {
                                            "title": "震度·震源に関する情報",
                                            "description": f"{time}頃、{hyponame}で地震がありました。\n{tsunami_info}",
                                            "color": 0x007cbf,
                                            "fields": [
                                                {
                                                    "name": "最大震度",
                                                    "value": f"{maxscale}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "震源",
                                                    "value": f"{hyponame}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "M",
                                                    "value": f"{magnitude}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "深さ",
                                                    "value": f"{depth}km",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "発生時刻",
                                                    "value": f"{time}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "ソース",
                                                    "value": f"{source}",
                                                    "inline": False
                                                }
                                            ]
                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---震度・震源に関する情報---\n{time}頃、{hyponame}で地震がありました。\n{tsunami_info}\n\n最大震度 {maxscale}\n\n震源 {hyponame}\nM {magnitude}\n深さ {depth}km\n発生時刻 {time}\nソース {source}\n\n[Generated by EQFast]"
                                }

                            elif type == "Foreign":
                                d_message = {
                                    "embeds": [
                                        {
                                            "title": "遠地地震に関する情報",
                                            "description": f"{time}頃、海外で大きな地震がありました。\n{tsunami_info}",
                                            "color": 0xd19e26,
                                            "fields": [
                                                {
                                                    "name": "震源",
                                                    "value": f"{hyponame}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "M",
                                                    "value": f"{magnitude}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "深さ",
                                                    "value": f"{depth}km",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "発生時刻",
                                                    "value": f"{time}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "ソース",
                                                    "value": f"{source}",
                                                    "inline": False
                                                }
                                            ]
                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---遠地地震情報---\n{time}頃、海外で大きな地震がありました。\n{tsunami_info}\n\n震源 {hyponame}\nM {magnitude}\n深さ {depth}km\n発生時刻 {time}ソース {source}\n\n[Generated by EQFast]"
                                }

                            elif type == "DetailScale":
                                shindo_rank = {
                                    "70": 7.0, "65": 6.2, "60": 6.1, "55": 5.2, "50": 5.1,
                                    "40": 4.0, "30": 3.0, "20": 2.0, "10": 1.0, "46": 0.0, None: 0.0
                                }

                                levels_map = {}
                                for p in parsed_json["points"]:
                                    scale = ms.get(int(p.get("scale", -1)), None)
                                    addr = p.get("addr", "")
                                    pref = p.get("pref", "不明")
                                    if scale is None:
                                        continue

                                    levels_map.setdefault(scale, {}).setdefault(pref, []).append(str(addr))

                                kakuchi_shindo = ""
                                for scale in sorted(levels_map.keys(), key=lambda s: shindo_rank.get(str(s), 0), reverse=True):
                                    shindo_label = "\n<震度" + str(ms.get(scale, scale)) + ">"
                                    kakuchi_shindo += f"{shindo_label}"

                                    for pref in sorted(levels_map[scale].keys()):
                                        kakuchi_shindo += f"\n[{pref}]\n"
                                        kakuchi_shindo += "\u3000".join(levels_map[scale][pref])

                                d_message = {
                                    "embeds": [
                                        {
                                            "title": "地震情報",
                                            "description": f"{time}頃、{hyponame}で地震がありました。\n{tsunami_info}",
                                            "color": 0x007cbf,
                                            "fields": [
                                                {
                                                    "name": "最大震度",
                                                    "value": f"{maxscale}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "震源",
                                                    "value": f"{hyponame}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "M",
                                                    "value": f"{magnitude}",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "深さ",
                                                    "value": f"{depth}km",
                                                    "inline": True
                                                },
                                                {
                                                    "name": "観測点ごとの震度",
                                                    "value": f"{kakuchi_shindo}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "発生時刻",
                                                    "value": f"{time}",
                                                    "inline": False
                                                },
                                                {
                                                    "name": "ソース",
                                                    "value": f"{source}",
                                                    "inline": False
                                                }
                                            ]
                                        }
                                    ]
                                }

                                sub_message = {
                                    "content": f"---地震情報---\n{time}頃、{hyponame}で地震がありました。\n{tsunami_info}\n\n最大震度 {maxscale}\n震源 {hyponame}\nM {magnitude}\n深さ {depth}km\n\n【観測点ごとの震度】{kakuchi_shindo}\n\n発生時刻 {time}\nソース {source}\n\n[Generated by EQFast]"
                                }

                            else:
                                d_message = {"content": f"その他のメッセージ:{type}"}
                                sub_message = {
                                    "content": "その他のメッセージ"
                                }

                            async with session.post(discordwh_url, json=d_message) as resp:
                                if resp.status in (200, 204):
                                    logger.info(f"Webhook OK:{resp.status}")
                                else:
                                    logger.error(f"Webhook failed:{resp.status}")

                            async with session.post(raw_wh, json=sub_message) as resp:
                                if resp.status in (200, 204):
                                    logger.info(f"raw_Webhook OK:{resp.status}")
                                else:
                                    logger.error(f"raw_Webhook failed:{resp.status}")

        except websockets.exceptions.ConnectionClosedError as e:
            logger.warning(f"{name} disconnected\n{e}")

        except Exception as e:
            logger.error(f"{name} error:{e}")

        logger.warning(f"{name} disconnected, retrying...")
        await asyncio.sleep(2)


async def main():
    wolfxurl = "wss://ws-api.wolfx.jp/jma_eew"
    p2purl = "wss://api.p2pquake.net/v2/ws"
    session = aiohttp.ClientSession()
    try:
        await asyncio.gather(
            wsconnect("wolfx", wolfxurl, session),
            wsconnect("p2p", p2purl, session),
        )
    finally:
        await session.close()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("SHUTDOWN TRYING")
    finally:
        logger.info("SHUTDOWN FINISHED")
