import requests
import json

testdata = {
    "type": "jma_eew",
    "Title": "緊急地震速報（警報）",
    "CodeType": "Ｍ、最大予測震度及び主要動到達予測時刻の緊急地震速報",
    "Issue": {
        "Source": "大阪",
        "Status": "通常"
    },
    "EventID": "20251125180119",
    "Serial": 2,
    "AnnouncedTime": "2025/11/25 18:01:25",
    "OriginTime": "2025/11/25 18:01:16",
    "Hypocenter": "熊本県阿蘇地方",
    "Latitude": 33.0,
    "Longitude": 131.1,
    "Magunitude": 5.5,
    "Depth": 10,
    "MaxIntensity": "5弱",
    "Accuracy": {
        "Epicenter": "IPF 法（5 点以上）",
        "Depth": "IPF 法（5 点以上）",
        "Magnitude": "P 相／全相混在"
    },
    "MaxIntChange": {
        "String": "ほとんど変化なし",
        "Reason": "不明、未設定時、キャンセル時"
    },
    "WarnArea": [
        {
            "Chiiki": "熊本県阿蘇",
            "Shindo1": "5弱",
            "Shindo2": "5弱",
            "Time": "//////",
            "Type": "警報",
            "Arrive": "既に到達と予測"
        },
        {
            "Chiiki": "大分県西部",
            "Shindo1": "4",
            "Shindo2": "4",
            "Time": "//////",
            "Type": "警報",
            "Arrive": "既に到達と予測"
        },
        {
            "Chiiki": "熊本県熊本",
            "Shindo1": "4",
            "Shindo2": "4",
            "Time": "//////",
            "Type": "警報",
            "Arrive": "既に到達と予測"
        },
        {
            "Chiiki": "大分県中部",
            "Shindo1": "4",
            "Shindo2": "4",
            "Time": "180127",
            "Type": "警報",
            "Arrive": "未到達"
        },
        {
            "Chiiki": "宮崎県北部山沿い",
            "Shindo1": "4",
            "Shindo2": "4",
            "Time": "180127",
            "Type": "警報",
            "Arrive": "未到達"
        },
        {
            "Chiiki": "佐賀県南部",
            "Shindo1": "4",
            "Shindo2": "4",
            "Time": "180137",
            "Type": "警報",
            "Arrive": "未到達"
        },
        {
            "Chiiki": "福岡県筑後",
            "Shindo1": "4",
            "Shindo2": "3",
            "Time": "180134",
            "Type": "警報",
            "Arrive": "未到達"
        }
    ],
    "isSea": False,
    "isTraining": False,
    "isAssumption": False,
    "isWarn": True,
    "isFinal": False,
    "isCancel": False,
    "OriginalText": "37 04 00 251125180125 C11 251125180116 ND20251125180119 NCN002 JD////////////// JN/// 740 N330 E1311 010 55 5- RK44454 RT01/// RC0//// EBI 740 S5-5- ////// 11 753 S0404 ////// 11 741 S0404 ////// 11 751 S0404 180127 10 761 S0404 180127 10 721 S0404 180137 10 713 S0403 180134 10 9999=",
    "Pond": "81"
}

W_Area = [area["Chiiki"] for area in testdata["WarnArea"]]
W_Area_send = "\u3000".join(W_Area)

wh_title = "緊急地震速報(警報) 第5報"
Hypocenter = "熊本県阿蘇地方"
Magunitude = "5.5"
Depth = "20"
MaxIntensity = "5弱"
AnnouncedTime = "2025/01/01 00:00:00"

sub_message = {
    "content": f"---⚠{wh_title}⚠---\n{Hypocenter}で地震\n身の安全を確保してください\nM {Magunitude}\u3000深さ {Depth}km\n推定最大震度 {MaxIntensity}\n対象地域\n{W_Area_send}\n発表時刻 {AnnouncedTime}\n[Generated by EQFast]"
}

senddata = json.loads(json.dumps(sub_message, default=list))

url = "https://discord.com/api/webhooks/1445007171007025153/c-kEsfx7ZjJ419UOeRTpFGy7B8MXr10WHd5RIwrQMNkQe9-ZVG4SyqAJYg_DZOp513uX"

res = requests.post(url, json=senddata)
