from eew_bot.models.eew import EEW


def build_raw_text(eew: EEW) -> str:
    kind = "警報" if eew.is_warn else "予報"
    final = " - 最終" if eew.is_final else ""

    return (
        f"---緊急地震速報（{kind}） 第{eew.report_no}報{final}---\n"
        f"{eew.hypo_name}で地震\n"
        f"M {eew.magnitude}\u3000深さ {eew.depth}km\n"
        f"推定最大震度 {eew.max_shindo}\n"
        f"発表時刻 {eew.report_time}\n"
        f"[Generated by EQFast]"
    )
