from eew_bot.models.eew import EEW
from eew_bot.models.quake import EarthquakeEvent
from datetime import datetime
from typing import Dict, Any

# 変数たち
scale_map = {
    10: "1", 20: "2", 30: "3", 40: "4",
    45: "5弱", 50: "5強", 55: "6弱", 60: "6強", 70: "7"
}

tsunami_text = {
    "None": "この地震による津波の心配はありません。",
    "Unknown": "津波の情報は不明です。今後の情報に注意してください。",
    "Checking": "津波などの詳しい情報は追ってお知らせします。",
    "NonEffective": "若干の海面変動があるかもしれませんが、被害の心配はありません。",
    "Watch": "現在、津波注意報を発表中です。",
    "Warning": "現在、津波予報等を発表中です。",
}

foreign_tsunami_text = {
    "None": "",
    "Unknown": "また、海外での津波に関する情報は不明です。",
    "Checking": "また、海外での津波に関する情報は調査中です。",
    "NonEffectiveNearby": "また、震源の近傍で小さな津波があるかもしれませんが、被害の心配はありません。",
    "WarningNearby": "また、震源の近傍では津波が発生する可能性があります。",
    "WarningPacific": "また、太平洋で津波の可能性があります。",
    "WarningPacificWide": "また、太平洋の広い範囲で津波の可能性があります。",
    "WarningIndian": "また、インド洋で津波の可能性があります。",
    "WarningIndianWide": "また、インド洋の広い範囲で津波の可能性があります。",
    "Potential": "また、震源の近傍では津波が発生する可能性があります。",
}

# embedの方


def build_eew_embed(eew: EEW) -> dict:
    kind = "警報" if eew.is_warn else "予報"
    final = " - 最終" if eew.is_final else ""

    title = f"緊急地震速報（{kind}） 第{eew.report_no}報{final}"

    warn_desc = ""

    warn_area_text = ""
    if eew.is_warn:
        warn_area_text = build_warn_area_text(eew.warn_area)
        warn_desc = "\u3000強い揺れに警戒"

    if eew.is_plum:
        eew_method = " (PLUM法による予測)"
        desc = f"{eew.hypo_name}で地震{eew_method}{warn_desc}"
    else:
        eew_method = ""
        desc = f"{eew.hypo_name}で地震{eew_method}{warn_desc}\nM {eew.magnitude}\u3000深さ {eew.depth}km"

    return {
        "embeds": [
            {
                "title": title,
                "description": desc,
                "color": 0x9C0000 if eew.is_warn else 0xDB9D00,
                "fields": [
                    {"name": "推定最大震度", "value": eew.max_shindo, "inline": False},
                    {"name": "対象地域", "value": warn_area_text, "inline": False},
                    {"name": "発表時刻", "value": eew.report_time, "inline": False},
                ]
            }
        ]
    }


def build_quake_embed(quake: EarthquakeEvent) -> Dict[str, Any]:
    max_scale = quake.earthquake.max_scale
    if max_scale >= 50:
        color = 0xAD0202
    elif max_scale >= 40:
        color = 0xFF8000
    elif max_scale >= 30:
        color = 0xFFC400
    else:
        color = 0x00A6FF

    max_scale_str = scale_map.get(max_scale, "不明")

    depth = quake.earthquake.hypocenter.depth

    if depth == 0:
        depth_str = "ごく浅い"
    elif depth == -1:
        depth_str = "不明"
    else:
        depth_str = f"{depth}km"

    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    magnitude = format_number(quake.earthquake.hypocenter.magnitude)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、{quake.earthquake.hypocenter.name}で地震がありました。"
    quake_desc += tsunami_str

    fields = [
        {
            "name": "最大震度",
            "value": max_scale_str,
            "inline": False
        },
        {
            "name": "震源地",
            "value": quake.earthquake.hypocenter.name,
            "inline": True
        },
        {
            "name": "M",
            "value": magnitude,
            "inline": True
        },
        {
            "name": "深さ",
            "value": depth_str,
            "inline": True
        },
    ]

    if quake.points:
        points_text = build_intensity_text(quake.points, scale_map)
        fields.append({
            "name": "各地の震度",
            "value": points_text,
            "inline": False
        })

    fields.append({
        "name": "発生時刻",
        "value": eq_time,
        "inline": False
    })

    embed = {
        "title": "地震情報",
        "description": quake_desc,
        "color": color,
        "fields": fields,
        "footer": {
            "text": f"ソース\n{quake.issue.source}"
        }
    }

    return {"embeds": [embed]}

# rawの方


def build_raw_text(eew: EEW) -> str:
    kind = "警報" if eew.is_warn else "予報"
    final = " - 最終" if eew.is_final else ""

    title = f"---緊急地震速報（{kind}） 第{eew.report_no}報{final}---\n"

    warn_desc = ""

    warn_area_text = ""
    if eew.is_warn or eew.is_plum:
        warn_area_text = build_warn_area_text(eew.warn_area)

        if eew.is_warn:
            warn_desc = "\u3000強い揺れに警戒"

    if eew.is_plum:
        eew_method = " (PLUM法による予測)"
        desc = f"{eew.hypo_name}で地震{eew_method}{warn_desc}"
    else:
        eew_method = ""
        desc = f"{eew.hypo_name}で地震{eew_method}{warn_desc}\nM {eew.magnitude}\u3000深さ {eew.depth}km"

    return (
        f"{title}"
        f"{desc}\n"
        f"推定最大震度 {eew.max_shindo}\n"
        f"{warn_area_text}\n"
        f"発表時刻 {eew.report_time}\n"
        "ソース:Wolfx Earthquake API"
        "\n\n[Generated by EQFast]"
    )


def build_quake_raw_text(quake: EarthquakeEvent) -> str:
    info_type = quake.issue.type

    if info_type == "ScalePrompt":
        return build_scaleprompt_raw(quake)
    elif info_type == "Destination":
        return build_destination_raw(quake)
    elif info_type == "ScaleAndDestination":
        return build_scaleanddestination_raw(quake)
    elif info_type == "DetailScale":
        return build_detailscale_raw(quake)
    elif info_type == "Foreign":
        return build_foreign_raw(quake)
    else:
        return "不明な情報種別です。"

# 共通の関数


def build_warn_area_text(warn_areas: list) -> str:
    if not warn_areas:
        return ""

    shindo_map = {}

    for area in warn_areas:
        shindo = area.get("Shindo1")
        chiiki = area.get("Chiiki")
        arrive_text = area.get("Arrive", "")

        if not shindo or not chiiki:
            continue

        suffix = arrive_suffix(arrive_text)

        shindo_map.setdefault(shindo, [])

        if not any(c == chiiki for c, _ in shindo_map[shindo]):
            shindo_map[shindo].append((chiiki, suffix))

    if not shindo_map:
        return ""

    text_lines = ["\n【対象地域】"]

    shindo_order = ["7", "6強", "6弱", "5強", "5弱", "4", "3"]

    for shindo in shindo_order:
        areas = shindo_map.get(shindo)
        if not areas:
            continue

        text_lines.append(f"[推定震度 {shindo}]")

        area_texts = []
        for chiiki, suffix in areas:
            area_texts.append(f"{chiiki}{suffix}\n")

        text_lines.append("".join(area_texts))

    return "\n".join(text_lines)


def arrive_suffix(arrive_text: str) -> str:
    if not arrive_text:
        return ""

    if "既に到達" in arrive_text:
        return "（到達）"

    if "主要動到達時刻の予測なし" in arrive_text:
        return "（到達予測無し）"

    return ""


def format_number(n):
    if isinstance(n, int) or n == int(n):
        return f"{n:.1f}"
    else:
        return str(n)


def format_depth(depth: int) -> str:
    if depth == 0:
        depth_str = "ごく浅い"
    elif depth == -1:
        depth_str = "不明"
    else:
        depth_str = f"{depth}km"

    return depth_str

# embedのみの関数


def build_intensity_text(points: list, scale_map: dict) -> str:
    if not points:
        return ""

    intensity_groups = {}
    for point in points:
        scale = scale_map.get(point.scale, "?")
        if scale not in intensity_groups:
            intensity_groups[scale] = []

        location = f"{point.pref}{point.addr}"
        if location not in intensity_groups[scale]:
            intensity_groups[scale].append(location)

    scale_order = ["7", "6強", "6弱", "5強", "5弱", "4", "3", "2", "1"]
    text_lines = []

    for scale in scale_order:
        if scale in intensity_groups:
            locations = intensity_groups[scale]
            text_lines.append(f"**<震度{scale}>**")

            location_text = "\u3000".join(locations)
            text_lines.append(location_text)

    return "\n".join(text_lines)

# rawのみの関数


def build_intensity_detail_text(points: list, scale_map: dict) -> str:
    if not points:
        return ""

    intensity_groups = {}
    for point in points:
        scale = scale_map.get(point.scale, "?")
        if scale not in intensity_groups:
            intensity_groups[scale] = {}

        pref = point.pref
        if pref not in intensity_groups[scale]:
            intensity_groups[scale][pref] = []

        intensity_groups[scale][pref].append(point.addr)

    scale_order = ["7", "6強", "6弱", "5強", "5弱", "4", "3", "2", "1"]
    text_lines = []

    for scale in scale_order:
        if scale not in intensity_groups:
            continue

        text_lines.append(f"\n<震度{scale}>")

        for pref, locations in intensity_groups[scale].items():
            text_lines.append(f"[{pref}]")

            locations_text = "\u3000".join(locations)
            text_lines.append(locations_text)

    return "\n".join(text_lines)

# 震度速報


def build_scaleprompt_raw(quake: EarthquakeEvent) -> str:
    max_scale_str = scale_map.get(quake.earthquake.max_scale, "不明")

    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、最大震度{max_scale_str}の地震がありました。"
    quake_desc += tsunami_str

    text = "---震度速報---\n"
    text += f"{quake_desc}\n\n"

    text += f"最大震度 {max_scale_str}\n"

    if quake.points:
        text += "\n【地域ごとの震度】\n"
        text += build_intensity_detail_text(quake.points, scale_map)

    text += f"\n\n発生時刻 {raw_eq_time.strftime('%Y年%m月%d日 %H:%M')}\n"
    text += f"ソース {quake.issue.source}・P2P地震情報 API"
    text += "\n\n[Generated by EQFast]"

    return text

# 震源情報


def build_destination_raw(quake: EarthquakeEvent) -> str:
    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    depth = quake.earthquake.hypocenter.depth
    depth_str = format_depth(depth)

    magnitude = format_number(quake.earthquake.hypocenter.magnitude)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、{quake.earthquake.hypocenter.name}で地震がありました。"
    quake_desc += tsunami_str

    text = "---震源に関する情報---\n"
    text += f"{quake_desc}\n\n"

    text += f"震源 {quake.earthquake.hypocenter.name}\n"
    text += f"M {magnitude}\n"
    text += f"深さ {depth_str}\n"

    text += f"\n発生時刻 {raw_eq_time.strftime('%Y年%m月%d日 %H:%M')}\n"
    text += f"ソース {quake.issue.source}・P2P地震情報 API"
    text += "\n\n[Generated by EQFast]"

    return text

# 震度・震源情報


def build_scaleanddestination_raw(quake: EarthquakeEvent) -> str:
    max_scale_str = scale_map.get(quake.earthquake.max_scale, "不明")
    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    depth = quake.earthquake.hypocenter.depth
    depth_str = format_depth(depth)

    magnitude = format_number(quake.earthquake.hypocenter.magnitude)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、{quake.earthquake.hypocenter.name}で地震がありました。"
    quake_desc += tsunami_str

    text = "---震度・震源に関する情報---\n"
    text += f"{quake_desc}\n\n"

    text += f"最大震度 {max_scale_str}\n"
    text += f"震源 {quake.earthquake.hypocenter.name}\n"
    text += f"M {magnitude}\n"
    text += f"深さ {depth_str}\n"

    if quake.points:
        text += "\n【詳しい震度】\n"
        text += build_intensity_detail_text(quake.points, scale_map)

    text += f"発生時刻 {raw_eq_time.strftime('%Y年%m月%d日 %H:%M')}\n"
    text += f"ソース {quake.issue.source}・P2P地震情報 API"
    text += "\n\n[Generated by EQFast]"

    return text

# 各地の震度


def build_detailscale_raw(quake: EarthquakeEvent) -> str:
    max_scale_str = scale_map.get(quake.earthquake.max_scale, "不明")
    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    depth = quake.earthquake.hypocenter.depth
    depth_str = format_depth(depth)

    magnitude = format_number(quake.earthquake.hypocenter.magnitude)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、{quake.earthquake.hypocenter.name}で地震がありました。"
    quake_desc += tsunami_str

    text = "---震度・震源に関する情報---\n"
    text += f"{quake_desc}\n\n"

    text += f"最大震度 {max_scale_str}\n"
    text += f"震源 {quake.earthquake.hypocenter.name}\n"
    text += f"M {magnitude}\n"
    text += f"深さ {depth_str}\n"

    if quake.points:
        text += "\n【観測点ごとの震度】\n"
        text += build_intensity_detail_text(quake.points, scale_map)

    text += f"\n発生時刻 {raw_eq_time.strftime('%Y年%m月%d日 %H:%M')}\n"
    text += f"ソース {quake.issue.source}・P2P地震情報 API"
    text += "\n\n[Generated by EQFast]"

    return text

# 遠地地震


def build_foreign_raw(quake: EarthquakeEvent) -> str:
    max_scale_str = scale_map.get(quake.earthquake.max_scale, "不明")
    tsunami_info = quake.earthquake.domestic_tsunami
    tsunami_str = tsunami_text.get(tsunami_info, tsunami_info)

    foreign_tsunami_info = quake.earthquake.foreign_tsunami
    foreign_tsunami_str = foreign_tsunami_text.get(foreign_tsunami_info, foreign_tsunami_info)

    depth = quake.earthquake.hypocenter.depth
    depth_str = format_depth(depth)

    magnitude = format_number(quake.earthquake.hypocenter.magnitude)

    raw_eq_time = datetime.strptime(quake.earthquake.time, "%Y/%m/%d %H:%M:%S")
    eq_time = raw_eq_time.strftime("%d日 %H:%M")

    quake_desc = f"{eq_time}頃、{quake.earthquake.hypocenter.name}で地震がありました。"
    quake_desc += tsunami_str
    quake_desc += foreign_tsunami_str

    text = "---遠地地震に関する情報---\n"
    text += f"{quake_desc}\n\n"

    text += f"最大震度 {max_scale_str}\n"
    text += f"震源 {quake.earthquake.hypocenter.name}\n"
    text += f"M {magnitude}\n"
    text += f"深さ {depth_str}\n"

    text += f"\n発生時刻 {raw_eq_time.strftime('%Y年%m月%d日 %H:%M')}\n"
    text += f"ソース {quake.issue.source}・P2P地震情報 API"
    text += "\n\n[Generated by EQFast]"

    return text

# その他
